### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zaoqi**

### CODE REVIEW

**Comment by andhie76** [comment]
diff --git a/README.md b/README.md
index 1a71386..d9ba37e 100644
--- a/README.md
+++ b/README.md
@@ -1,5 +1,8 @@
 TermuxArch
 ===============
+
+*Moved. Visit [https://github.com/sdrausty/TermuxArch](https://github.com/sdrausty/TermuxArch).*
+
 [Join the chat at https://gitter.im/termux](https://gitter.im/termux)
 
 This Termux bash shell script will attempt to set up Arch Linux on Amazon Fire OS, Android and Chromebook using [Termux](https://termux.com)

**Comment by zaoqi** [comment]
@andhie76 ?

**Comment by sdrausty** [comment]
https://github.com/sdrausty?tab=repositories&q=arch&language=Shell
https://github.com/TermuxArch

**Comment by zaoqi** [comment]
@sdrausty ????????????

**Comment by sdrausty** [comment]
> https://github.com/TermuxArch

**Comment by sdrausty** [comment]
> Moved
Moving

**Comment by sdrausty** [comment]
Jun 8, 2019
> Moved

Moving...

**Comment by sdrausty** [comment]
@zaoqi & @andhie76 
>  ????????????

https://f-droid.org/repo/com.termux_69_src.tar.gz
> 404 Page Not Found

**Comment by sdrausty** [comment]
https://f-droid.org/en/packages/com.termux/

**Comment by sdrausty** [comment]
?

**Comment by sdrausty** [comment]
404 ?

**Pull request closed without merging**
